baseurl = "https://example.com/"
title = "console-demo"
theme = "hugo-theme-console"
languageCode = "en-us"
copyright = "Copyright Â© 2024 Albert Author."

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = false

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast" 

  # Show a small logo at footer
  # To change the logo, please name the image file "logo.png" and put it under assets/images/
  footerImg = false

  # Show favicon
  # To change the icon, please convert the icon to "favicon.ico" and put it under assets/images/
  favicon = false

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Posts"
  url = "posts/"
  
  [[params.navlinks]]
  name = "Photos"
  url = "photos/"
  
  [[params.navlinks]]
  name = "Categories"
  url = "categories/"
